# if we have the react-router-dom(to navigate from one route to another route in our project ) functionalith in our react application in theat we case we have to create this file in our public folder of the our project folder 

[[redirects]] 

from = "/*"
to = "/index.html" 
status = 200 

